export const Images = {
    checkIcon: require('../assets/images/CheckMark.png'),
    englishEmojiIcon: require('../assets/images/HelloEmoji.gif'),
    splashScreenLogo: require('../assets/images/SplashScreenLogo.png'),
    superHeroImage: require('../assets/images/SuperHero.png'),
    geographyImage: require('../assets/images/Geography.png'),
    happyFairyImage: require('../assets/images/HappyFairy.png'),
    historyImage: require('../assets/images/HistoryImage.png'),
    scienceImage: require('../assets/images/ScienceImage.png'),
    animalsImage: require('../assets/images/AnimalsImage.png'),
    playAudioImage: require('../assets/images/PlayMusic.png'),
    namasteHandGif: require('../assets/images/NamasteHand.gif'),
    wavingHandGif: require('../assets/images/WavingHand.gif'),
    namasteHindi: require('../assets/images/NamasteHindi.png'),
    toodlers1: require('../assets/images/Toodlers.png'),
    toodlers3: require('../assets/images/SchoolToodlers.png'),
    toodlers2: require('../assets/images/YoungMindToodlers.png'),
  };